# Generated by Django 5.0.6 on 2024-05-22 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('num_processors', models.IntegerField()),
                ('memory_capacity', models.IntegerField()),
                ('storage_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('launch_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='servops.server')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='server_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servops.servertype'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('launch_date', models.DateField()),
                ('memory_used', models.IntegerField()),
                ('required_memory', models.IntegerField()),
                ('launch_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='servops.server')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_usages', to='servops.application')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_usages', to='servops.service')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='services',
            field=models.ManyToManyField(related_name='applications', to='servops.service'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='servops.servuser'),
        ),
    ]
