# Generated by Django 5.0 on 2024-06-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='logo',
            field=models.ImageField(blank=True, default='logos/logo.png', null=True, upload_to='logos/'),
        ),
    ]
